import type { NextPage } from 'next';
import { useEffect } from 'react';
import Link from 'next/link';
import Head from 'next/head';
import Script from 'next/script';
import styles from '../../styles/Skills.module.css';

const Skills: NextPage = () => {
  return (
    <div className={styles.bg}>
      <Head>
        <title>Скилы</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.title}>My skills list</div>

      <div className={styles.footer}>
        <div className={styles.footerBlock}>
          <Link href="/" replace>
            Home
          </Link>
          <span>My skills</span>
          <button id="soundButton" className={styles.soundButton} type="button">
            <img id="soundButtonImage" src="/images/sound_ON.png" alt="sound_ON" />
            <span id="soundButtonLabel" className={styles.soundButtonLabel}>
              <b>Sound On</b>
            </span>
          </button>
        </div>
      </div>

      <Script src="./libs/CSSPlugin.min.js" strategy="beforeInteractive" />
      <Script src="./libs/TweenLite.min.js" strategy="beforeInteractive" />
      <Script src="./libs/TimelineLite.min.js" strategy="beforeInteractive" />
      <Script src="./libs/EasePack.min.js" strategy="beforeInteractive" />
    </div>
  );
};

export default Skills;
