import type { NextPage } from 'next';
import Head from 'next/head';

const Portfolio: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Портфолио</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Портфолио</main>
    </div>
  );
};

export default Portfolio;
