name: Checks

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current year
        id: year
        run: echo "year=$('%Y')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: Install libs
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Build the app
        run: npm run build
        env:
          YEAR: ${{ steps.year.outputs.year }}
