name: Checks

on:
  push:
    branches:
    - dev

  pull_request_target:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install libs
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn type-check

      - name: Build the app
        run: yarn build

      - name: Vercel Action
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
