name: Checks

on:
  push:
    branches:
    - dev

  pull_request_target:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current year
        run: echo "YEAR=$(date +'%Y')" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Install libs
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Build the app
        run: YEAR=${{ env.YEAR }} npm run build
        env:
          YEAR: ${{ env.YEAR }}

      - name: Vercel Action
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
