name: Build 4life.work

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - name: Get current year
        run: echo "YEAR=$(date +'%Y')" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Install libs
        run: npm i

      - name: Build the app
        run: YEAR=${{ env.YEAR }} npm run build
        env:
          YEAR: ${{ env.YEAR }}

      - name: Vercel Action
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: .next
          vercel-args: '--prod '

