name: Build 4life.work

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - name: Get current year
        id: year
        run: echo "::set-output name=year::$('%Y')"
      - uses: actions/checkout@v2
      - name: Install libs
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Build the app
        run: npm run build
        env:
          YEAR: ${{ steps.year.outputs.year }}

      - name: Vercel Action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        uses: amondnet/vercel-action@v20.0.1

