name: Version Auto Increment

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_BOT_ACCESS_TOKEN }}
      - run: git config --global user.name 'bot'
      - run: git config --global user.email 'bot@4life.work'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
